#spring.application.name=eureka-client-02
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
## spring cloud access&secret config
## 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****

eureka:
  client:
    serviceUrl: #注册中心
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8763
spring:
  application:
    name: eureka-client-01  #服务集群，Ribbon负载均衡

